pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - us-central1-b.gcp.pangeo.io
        letsencrypt:
          contactEmail: rpa@ldeo.columbia.edu
      service:
        loadBalancerIP: 104.197.6.79
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-us-central1b-prod-dask-gateway.prod"
    singleuser:
      extraEnv:
        # TODO: DNS
        DASK_GATEWAY__ADDRESS: "https://us-central1-b.gcp.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-us-central1b-prod-dask-gateway.prod:80"
